function [ Track ] = FSAEMichigan2015_Schraeger_Version3( )
%FSAE 2015 Michigan Endurance Track
%   View Solidworks Part: "FSAE Map Michigan 2015_Schraeger.SLDPRT" for
%   measurements
%   The defined track matches the race line data generated by Reiley
%   Schraeger
%   of www.fsaesim.com
%   http://students.sae.org/cds/formulaseries/fsae/autocross2015.pdf
%   Reiley Schraeger / lamborghinidoor@yahoo.com

%   Defines section data, one straight section followed by several curved sections.
%   FSAE 2015 Autocross times:  Min Time: 46.944, Max Time: 68.069


SectionMatrix = [

    
546.09,	414.51
315.36,	414.51
308.35,	297.56
495.58,	521.63
527.84,	0
346.86,	0
1758.04,	0
295.64,	0
430.91,	0
487.6,	799.32
693.59,	1143.03
470.99,	585.92
364.32,	0
591.77,	630.25
765.27,	728.18
1077.03,	1208.6
553.88,	705.28
441.8,	541.07
515.72,	609.75
638.16,	553.01
1734.06,	0
791.43,	1746.52
334.3,	292.18
1377.57,	1502.3
956.31,	922.24
474.14,	590.69
654.26,	0
338.29,	0
630.03,	468.93
909.57,	468.93
407.24,	0
661.5,	0
461.41,	0
858.1,	0
690.87,	685.21
1023.9,	1239.85
270.79,	0
333.47,	297
226.71,	204.44
542.84,	638.29
412.76,	524.92
422.32,	389.35
494.34,	0
823.54,	0
1941.29,	0
616.33,	0
786.7,	2108.23
511.48,	423.4
422.2,	133.25
928.88,	409.98
274.1,	157.92
778.55,	0
408.41,	0
841.33,	1345.6
496.19,	798.76
446,	554.6
392.47,	572.57
492.21,	650.4
455.8,	445.35
1309.1,	1648.44
229.96,	221.83
1373.64,	577.96
787.86,	0



    ]; % inches  [Length,Radius (O represents a straight)]


N = length(SectionMatrix);

% Builds array of TrackSection objects
for i=1:N
    if SectionMatrix(i,2)
        Length = SectionMatrix(i,1);
        Radius = SectionMatrix(i,2);
        TS = TrackSection(Length,Radius,i);
        TSArray(i) = TS;
    else
        Length = SectionMatrix(i,1);
        TS = TrackSection(Length,0,i);
        TSArray(i) = TS;
    end
end

% Calls TestTrack Constructor
Track = TestTrack(TSArray);


end


